
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import SignInComponent from "@/components/SignInComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KaziKYC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="light">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
          <SignedOut>
            <SignInComponent/>
            <main className="flex-1 min-h-screen">{children}</main>
          </SignedOut>
          <SignedIn>
            <div>
              <Navbar />
              <main className="flex-1 min-h-screen ml-[250px]">{children}</main>
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}