import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import SignInComponent from "@/components/SignInComponent";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KaziKYC",
  description: "Generated by create next app",
};

function LoadingFallback() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="text-center space-y-4">
        <div className="flex justify-center">
          <span className="loading loading-spinner loading-lg text-blue-600"></span>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold text-gray-900">Loading...</h2>
          <p className="text-gray-600">Please wait while we prepare your experience</p>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="light">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
          <SignedOut>
            <SignInComponent/>
          </SignedOut>
          <SignedIn>
            <Suspense fallback={<LoadingFallback />}>
              <div className="flex min-h-screen">
                <Navbar />
                <main className="flex-1 overflow-auto">
                  {children}
                </main>
              </div>
            </Suspense>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
